### ISSUE TITLE
Is it necessay to have a HDMI display modual for Pynq-Z1 which has no VGA ?

### ISSUE THREAD

**Issue by hrpccs** [howardlau1999/yatcpu#27]
The Pynq-Z1 has no VGA and we just want to use the FPGA part of the board. So if we want to display something , we need to write a HDMI display modual with chisel like the vgadisplay module.

**Comment by howardlau1999** [comment]
yes, this is necessary and if you like you can implement the module and open a pull request

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: hrpccs ***@***.***>
Sent: Saturday, January 22, 2022 3:55:34 PM
To: howardlau1999/yatcpu ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [howardlau1999/yatcpu] Is it necessay to have a HDMI display modual for Pynq-Z1 which has no VGA ? (Issue #27)


The Pynq-Z1 has no VGA and we just want to use the FPGA part of the board. So if we want to display something , we need to write a HDMI display modual with chisel like the vgadisplay module.

―
